var employee = [101, "Batra", "Account", 40000];
employee[0];
employee[1];
employee[2];
employee.push(102, "Shroya", "Purchase", 23000);
console.log(employee);
var employees;
employees = [[101, "Khanna"], [102, "Shakshi"], [103, "Khurana"]];
console.log(employees);
console.log(employees[0][0]);
console.log(employees[0][1]);
employees.push([104, "Talwar"]);
